#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-klob
Version  : 0.2.1
Release  : 1
URL      : https://repo1.maven.org/maven2/com/github/shyiko/klob/klob/0.2.1/klob-0.2.1-sources.jar
Source0  : https://repo1.maven.org/maven2/com/github/shyiko/klob/klob/0.2.1/klob-0.2.1-sources.jar
Source1  : https://repo1.maven.org/maven2/com/github/shyiko/klob/klob/0.2.1/klob-0.2.1.jar
Source2  : https://repo1.maven.org/maven2/com/github/shyiko/klob/klob/0.2.1/klob-0.2.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: mvn-klob-data = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
No detailed description available

%package data
Summary: data components for the mvn-klob package.
Group: Data

%description data
data components for the mvn-klob package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/shyiko/klob/klob/0.2.1
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/com/github/shyiko/klob/klob/0.2.1/klob-0.2.1-sources.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/shyiko/klob/klob/0.2.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/github/shyiko/klob/klob/0.2.1/klob-0.2.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/shyiko/klob/klob/0.2.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/github/shyiko/klob/klob/0.2.1/klob-0.2.1.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/github/shyiko/klob/klob/0.2.1/klob-0.2.1-sources.jar
/usr/share/java/.m2/repository/com/github/shyiko/klob/klob/0.2.1/klob-0.2.1.jar
/usr/share/java/.m2/repository/com/github/shyiko/klob/klob/0.2.1/klob-0.2.1.pom
